package ietflt

var iso6391s = map[string]string{
	"af":             "af",
	"af-NA":          "af",
	"af-ZA":          "af",
	"agq":            "agq",
	"agq-CM":         "agq",
	"ak":             "ak",
	"ak-GH":          "ak",
	"am":             "am",
	"am-ET":          "am",
	"ar":             "ar",
	"ar-001":         "ar",
	"ar-AE":          "ar",
	"ar-BH":          "ar",
	"ar-DJ":          "ar",
	"ar-DZ":          "ar",
	"ar-EG":          "ar",
	"ar-EH":          "ar",
	"ar-ER":          "ar",
	"ar-IL":          "ar",
	"ar-IQ":          "ar",
	"ar-JO":          "ar",
	"ar-KM":          "ar",
	"ar-KW":          "ar",
	"ar-LB":          "ar",
	"ar-LY":          "ar",
	"ar-MA":          "ar",
	"ar-MR":          "ar",
	"ar-OM":          "ar",
	"ar-PS":          "ar",
	"ar-QA":          "ar",
	"ar-SA":          "ar",
	"ar-SD":          "ar",
	"ar-SO":          "ar",
	"ar-SS":          "ar",
	"ar-SY":          "ar",
	"ar-TD":          "ar",
	"ar-TN":          "ar",
	"ar-YE":          "ar",
	"as":             "as",
	"as-IN":          "as",
	"asa":            "asa",
	"asa-TZ":         "asa",
	"ast":            "ast",
	"ast-ES":         "ast",
	"az":             "az",
	"az-Cyrl":        "az",
	"az-Cyrl-AZ":     "az",
	"az-Latn":        "az",
	"az-Latn-AZ":     "az",
	"bas":            "bas",
	"bas-CM":         "bas",
	"be":             "be",
	"be-BY":          "be",
	"bem":            "bem",
	"bem-ZM":         "bem",
	"bez":            "bez",
	"bez-TZ":         "bez",
	"bg":             "bg",
	"bg-BG":          "bg",
	"bm":             "bm",
	"bm-ML":          "bm",
	"bn":             "bn",
	"bn-BD":          "bn",
	"bn-IN":          "bn",
	"bo":             "bo",
	"bo-CN":          "bo",
	"bo-IN":          "bo",
	"br":             "br",
	"br-FR":          "br",
	"brx":            "brx",
	"brx-IN":         "brx",
	"bs":             "bs",
	"bs-Cyrl":        "bs",
	"bs-Cyrl-BA":     "bs",
	"bs-Latn":        "bs",
	"bs-Latn-BA":     "bs",
	"ca":             "ca",
	"ca-AD":          "ca",
	"ca-ES":          "ca",
	"ca-ES-VALENCIA": "ca",
	"ca-FR":          "ca",
	"ca-IT":          "ca",
	"ce":             "ce",
	"ce-RU":          "ce",
	"cgg":            "cgg",
	"cgg-UG":         "cgg",
	"chr":            "chr",
	"chr-US":         "chr",
	"ckb":            "ckb",
	"ckb-IQ":         "ckb",
	"ckb-IR":         "ckb",
	"cs":             "cs",
	"cs-CZ":          "cs",
	"cu":             "cu",
	"cu-RU":          "cu",
	"cy":             "cy",
	"cy-GB":          "cy",
	"da":             "da",
	"da-DK":          "da",
	"da-GL":          "da",
	"dav":            "dav",
	"dav-KE":         "dav",
	"de":             "de",
	"de-AT":          "de",
	"de-BE":          "de",
	"de-CH":          "de",
	"de-DE":          "de",
	"de-IT":          "de",
	"de-LI":          "de",
	"de-LU":          "de",
	"dje":            "dje",
	"dje-NE":         "dje",
	"dsb":            "dsb",
	"dsb-DE":         "dsb",
	"dua":            "dua",
	"dua-CM":         "dua",
	"dyo":            "dyo",
	"dyo-SN":         "dyo",
	"dz":             "dz",
	"dz-BT":          "dz",
	"ebu":            "ebu",
	"ebu-KE":         "ebu",
	"ee":             "ee",
	"ee-GH":          "ee",
	"ee-TG":          "ee",
	"el":             "el",
	"el-CY":          "el",
	"el-GR":          "el",
	"en":             "en",
	"en-001":         "en",
	"en-150":         "en",
	"en-AG":          "en",
	"en-AI":          "en",
	"en-AS":          "en",
	"en-AT":          "en",
	"en-AU":          "en",
	"en-BB":          "en",
	"en-BE":          "en",
	"en-BI":          "en",
	"en-BM":          "en",
	"en-BS":          "en",
	"en-BW":          "en",
	"en-BZ":          "en",
	"en-CA":          "en",
	"en-CC":          "en",
	"en-CH":          "en",
	"en-CK":          "en",
	"en-CM":          "en",
	"en-CX":          "en",
	"en-CY":          "en",
	"en-DE":          "en",
	"en-DG":          "en",
	"en-DK":          "en",
	"en-DM":          "en",
	"en-ER":          "en",
	"en-FI":          "en",
	"en-FJ":          "en",
	"en-FK":          "en",
	"en-FM":          "en",
	"en-GB":          "en",
	"en-GD":          "en",
	"en-GG":          "en",
	"en-GH":          "en",
	"en-GI":          "en",
	"en-GM":          "en",
	"en-GU":          "en",
	"en-GY":          "en",
	"en-HK":          "en",
	"en-IE":          "en",
	"en-IL":          "en",
	"en-IM":          "en",
	"en-IN":          "en",
	"en-IO":          "en",
	"en-JE":          "en",
	"en-JM":          "en",
	"en-KE":          "en",
	"en-KI":          "en",
	"en-KN":          "en",
	"en-KY":          "en",
	"en-LC":          "en",
	"en-LR":          "en",
	"en-LS":          "en",
	"en-MG":          "en",
	"en-MH":          "en",
	"en-MO":          "en",
	"en-MP":          "en",
	"en-MS":          "en",
	"en-MT":          "en",
	"en-MU":          "en",
	"en-MW":          "en",
	"en-MY":          "en",
	"en-NA":          "en",
	"en-NF":          "en",
	"en-NG":          "en",
	"en-NL":          "en",
	"en-NR":          "en",
	"en-NU":          "en",
	"en-NZ":          "en",
	"en-PG":          "en",
	"en-PH":          "en",
	"en-PK":          "en",
	"en-PN":          "en",
	"en-PR":          "en",
	"en-PW":          "en",
	"en-RW":          "en",
	"en-SB":          "en",
	"en-SC":          "en",
	"en-SD":          "en",
	"en-SE":          "en",
	"en-SG":          "en",
	"en-SH":          "en",
	"en-SI":          "en",
	"en-SL":          "en",
	"en-SS":          "en",
	"en-SX":          "en",
	"en-SZ":          "en",
	"en-TC":          "en",
	"en-TK":          "en",
	"en-TO":          "en",
	"en-TT":          "en",
	"en-TV":          "en",
	"en-TZ":          "en",
	"en-UG":          "en",
	"en-UM":          "en",
	"en-US":          "en",
	"en-US-POSIX":    "en",
	"en-VC":          "en",
	"en-VG":          "en",
	"en-VI":          "en",
	"en-VU":          "en",
	"en-WS":          "en",
	"en-ZA":          "en",
	"en-ZM":          "en",
	"en-ZW":          "en",
	"eo":             "eo",
	"eo-001":         "eo",
	"es":             "es",
	"es-419":         "es",
	"es-AR":          "es",
	"es-BO":          "es",
	"es-BR":          "es",
	"es-BZ":          "es",
	"es-CL":          "es",
	"es-CO":          "es",
	"es-CR":          "es",
	"es-CU":          "es",
	"es-DO":          "es",
	"es-EA":          "es",
	"es-EC":          "es",
	"es-ES":          "es",
	"es-GQ":          "es",
	"es-GT":          "es",
	"es-HN":          "es",
	"es-IC":          "es",
	"es-MX":          "es",
	"es-NI":          "es",
	"es-PA":          "es",
	"es-PE":          "es",
	"es-PH":          "es",
	"es-PR":          "es",
	"es-PY":          "es",
	"es-SV":          "es",
	"es-US":          "es",
	"es-UY":          "es",
	"es-VE":          "es",
	"et":             "et",
	"et-EE":          "et",
	"eu":             "eu",
	"eu-ES":          "eu",
	"ewo":            "ewo",
	"ewo-CM":         "ewo",
	"fa":             "fa",
	"fa-AF":          "fa",
	"fa-IR":          "fa",
	"ff":             "ff",
	"ff-CM":          "ff",
	"ff-GN":          "ff",
	"ff-MR":          "ff",
	"ff-SN":          "ff",
	"fi":             "fi",
	"fi-FI":          "fi",
	"fil":            "fil",
	"fil-PH":         "fil",
	"fo":             "fo",
	"fo-DK":          "fo",
	"fo-FO":          "fo",
	"fr":             "fr",
	"fr-BE":          "fr",
	"fr-BF":          "fr",
	"fr-BI":          "fr",
	"fr-BJ":          "fr",
	"fr-BL":          "fr",
	"fr-CA":          "fr",
	"fr-CD":          "fr",
	"fr-CF":          "fr",
	"fr-CG":          "fr",
	"fr-CH":          "fr",
	"fr-CI":          "fr",
	"fr-CM":          "fr",
	"fr-DJ":          "fr",
	"fr-DZ":          "fr",
	"fr-FR":          "fr",
	"fr-GA":          "fr",
	"fr-GF":          "fr",
	"fr-GN":          "fr",
	"fr-GP":          "fr",
	"fr-GQ":          "fr",
	"fr-HT":          "fr",
	"fr-KM":          "fr",
	"fr-LU":          "fr",
	"fr-MA":          "fr",
	"fr-MC":          "fr",
	"fr-MF":          "fr",
	"fr-MG":          "fr",
	"fr-ML":          "fr",
	"fr-MQ":          "fr",
	"fr-MR":          "fr",
	"fr-MU":          "fr",
	"fr-NC":          "fr",
	"fr-NE":          "fr",
	"fr-PF":          "fr",
	"fr-PM":          "fr",
	"fr-RE":          "fr",
	"fr-RW":          "fr",
	"fr-SC":          "fr",
	"fr-SN":          "fr",
	"fr-SY":          "fr",
	"fr-TD":          "fr",
	"fr-TG":          "fr",
	"fr-TN":          "fr",
	"fr-VU":          "fr",
	"fr-WF":          "fr",
	"fr-YT":          "fr",
	"fur":            "fur",
	"fur-IT":         "fur",
	"fy":             "fy",
	"fy-NL":          "fy",
	"ga":             "ga",
	"ga-IE":          "ga",
	"gd":             "gd",
	"gd-GB":          "gd",
	"gl":             "gl",
	"gl-ES":          "gl",
	"gsw":            "gsw",
	"gsw-CH":         "gsw",
	"gsw-FR":         "gsw",
	"gsw-LI":         "gsw",
	"gu":             "gu",
	"gu-IN":          "gu",
	"guz":            "guz",
	"guz-KE":         "guz",
	"gv":             "gv",
	"gv-IM":          "gv",
	"ha":             "ha",
	"ha-GH":          "ha",
	"ha-NE":          "ha",
	"ha-NG":          "ha",
	"haw":            "haw",
	"haw-US":         "haw",
	"he":             "he",
	"he-IL":          "he",
	"hi":             "hi",
	"hi-IN":          "hi",
	"hr":             "hr",
	"hr-BA":          "hr",
	"hr-HR":          "hr",
	"hsb":            "hsb",
	"hsb-DE":         "hsb",
	"hu":             "hu",
	"hu-HU":          "hu",
	"hy":             "hy",
	"hy-AM":          "hy",
	"id":             "id",
	"id-ID":          "id",
	"ig":             "ig",
	"ig-NG":          "ig",
	"ii":             "ii",
	"ii-CN":          "ii",
	"is":             "is",
	"is-IS":          "is",
	"it":             "it",
	"it-CH":          "it",
	"it-IT":          "it",
	"it-SM":          "it",
	"it-VA":          "it",
	"ja":             "ja",
	"ja-JP":          "ja",
	"jgo":            "jgo",
	"jgo-CM":         "jgo",
	"jmc":            "jmc",
	"jmc-TZ":         "jmc",
	"ka":             "ka",
	"ka-GE":          "ka",
	"kab":            "kab",
	"kab-DZ":         "kab",
	"kam":            "kam",
	"kam-KE":         "kam",
	"kde":            "kde",
	"kde-TZ":         "kde",
	"kea":            "kea",
	"kea-CV":         "kea",
	"khq":            "khq",
	"khq-ML":         "khq",
	"ki":             "ki",
	"ki-KE":          "ki",
	"kk":             "kk",
	"kk-KZ":          "kk",
	"kkj":            "kkj",
	"kkj-CM":         "kkj",
	"kl":             "kl",
	"kl-GL":          "kl",
	"kln":            "kln",
	"kln-KE":         "kln",
	"km":             "km",
	"km-KH":          "km",
	"kn":             "kn",
	"kn-IN":          "kn",
	"ko":             "ko",
	"ko-KP":          "ko",
	"ko-KR":          "ko",
	"kok":            "kok",
	"kok-IN":         "kok",
	"ks":             "ks",
	"ks-IN":          "ks",
	"ksb":            "ksb",
	"ksb-TZ":         "ksb",
	"ksf":            "ksf",
	"ksf-CM":         "ksf",
	"ksh":            "ksh",
	"ksh-DE":         "ksh",
	"kw":             "kw",
	"kw-GB":          "kw",
	"ky":             "ky",
	"ky-KG":          "ky",
	"lag":            "lag",
	"lag-TZ":         "lag",
	"lb":             "lb",
	"lb-LU":          "lb",
	"lg":             "lg",
	"lg-UG":          "lg",
	"lkt":            "lkt",
	"lkt-US":         "lkt",
	"ln":             "ln",
	"ln-AO":          "ln",
	"ln-CD":          "ln",
	"ln-CF":          "ln",
	"ln-CG":          "ln",
	"lo":             "lo",
	"lo-LA":          "lo",
	"lrc":            "lrc",
	"lrc-IQ":         "lrc",
	"lrc-IR":         "lrc",
	"lt":             "lt",
	"lt-LT":          "lt",
	"lu":             "lu",
	"lu-CD":          "lu",
	"luo":            "luo",
	"luo-KE":         "luo",
	"luy":            "luy",
	"luy-KE":         "luy",
	"lv":             "lv",
	"lv-LV":          "lv",
	"mas":            "mas",
	"mas-KE":         "mas",
	"mas-TZ":         "mas",
	"mer":            "mer",
	"mer-KE":         "mer",
	"mfe":            "mfe",
	"mfe-MU":         "mfe",
	"mg":             "mg",
	"mg-MG":          "mg",
	"mgh":            "mgh",
	"mgh-MZ":         "mgh",
	"mgo":            "mgo",
	"mgo-CM":         "mgo",
	"mk":             "mk",
	"mk-MK":          "mk",
	"ml":             "ml",
	"ml-IN":          "ml",
	"mn":             "mn",
	"mn-MN":          "mn",
	"mr":             "mr",
	"mr-IN":          "mr",
	"ms":             "ms",
	"ms-BN":          "ms",
	"ms-MY":          "ms",
	"ms-SG":          "ms",
	"mt":             "mt",
	"mt-MT":          "mt",
	"mua":            "mua",
	"mua-CM":         "mua",
	"my":             "my",
	"my-MM":          "my",
	"mzn":            "mzn",
	"mzn-IR":         "mzn",
	"naq":            "naq",
	"naq-NA":         "naq",
	"nb":             "nb",
	"nb-NO":          "nb",
	"nb-SJ":          "nb",
	"nd":             "nd",
	"nd-ZW":          "nd",
	"nds":            "nds",
	"nds-DE":         "nds",
	"nds-NL":         "nds",
	"ne":             "ne",
	"ne-IN":          "ne",
	"ne-NP":          "ne",
	"nl":             "nl",
	"nl-AW":          "nl",
	"nl-BE":          "nl",
	"nl-BQ":          "nl",
	"nl-CW":          "nl",
	"nl-NL":          "nl",
	"nl-SR":          "nl",
	"nl-SX":          "nl",
	"nmg":            "nmg",
	"nmg-CM":         "nmg",
	"nn":             "nn",
	"nn-NO":          "nn",
	"nnh":            "nnh",
	"nnh-CM":         "nnh",
	"nus":            "nus",
	"nus-SS":         "nus",
	"nyn":            "nyn",
	"nyn-UG":         "nyn",
	"om":             "om",
	"om-ET":          "om",
	"om-KE":          "om",
	"or":             "or",
	"or-IN":          "or",
	"os":             "os",
	"os-GE":          "os",
	"os-RU":          "os",
	"pa":             "pa",
	"pa-Arab":        "pa",
	"pa-Arab-PK":     "pa",
	"pa-Guru":        "pa",
	"pa-Guru-IN":     "pa",
	"pl":             "pl",
	"pl-PL":          "pl",
	"prg":            "prg",
	"prg-001":        "prg",
	"ps":             "ps",
	"ps-AF":          "ps",
	"pt":             "pt",
	"pt-AO":          "pt",
	"pt-BR":          "pt",
	"pt-CH":          "pt",
	"pt-CV":          "pt",
	"pt-GQ":          "pt",
	"pt-GW":          "pt",
	"pt-LU":          "pt",
	"pt-MO":          "pt",
	"pt-MZ":          "pt",
	"pt-PT":          "pt",
	"pt-ST":          "pt",
	"pt-TL":          "pt",
	"qu":             "qu",
	"qu-BO":          "qu",
	"qu-EC":          "qu",
	"qu-PE":          "qu",
	"rm":             "rm",
	"rm-CH":          "rm",
	"rn":             "rn",
	"rn-BI":          "rn",
	"ro":             "ro",
	"ro-MD":          "ro",
	"ro-RO":          "ro",
	"rof":            "rof",
	"rof-TZ":         "rof",
	"root":           "root",
	"ru":             "ru",
	"ru-BY":          "ru",
	"ru-KG":          "ru",
	"ru-KZ":          "ru",
	"ru-MD":          "ru",
	"ru-RU":          "ru",
	"ru-UA":          "ru",
	"rw":             "rw",
	"rw-RW":          "rw",
	"rwk":            "rwk",
	"rwk-TZ":         "rwk",
	"sah":            "sah",
	"sah-RU":         "sah",
	"saq":            "saq",
	"saq-KE":         "saq",
	"sbp":            "sbp",
	"sbp-TZ":         "sbp",
	"se":             "se",
	"se-FI":          "se",
	"se-NO":          "se",
	"se-SE":          "se",
	"seh":            "seh",
	"seh-MZ":         "seh",
	"ses":            "ses",
	"ses-ML":         "ses",
	"sg":             "sg",
	"sg-CF":          "sg",
	"shi":            "shi",
	"shi-Latn":       "shi",
	"shi-Latn-MA":    "shi",
	"shi-Tfng":       "shi",
	"shi-Tfng-MA":    "shi",
	"si":             "si",
	"si-LK":          "si",
	"sk":             "sk",
	"sk-SK":          "sk",
	"sl":             "sl",
	"sl-SI":          "sl",
	"smn":            "smn",
	"smn-FI":         "smn",
	"sn":             "sn",
	"sn-ZW":          "sn",
	"so":             "so",
	"so-DJ":          "so",
	"so-ET":          "so",
	"so-KE":          "so",
	"so-SO":          "so",
	"sq":             "sq",
	"sq-AL":          "sq",
	"sq-MK":          "sq",
	"sq-XK":          "sq",
	"sr":             "sr",
	"sr-Cyrl":        "sr",
	"sr-Cyrl-BA":     "sr",
	"sr-Cyrl-ME":     "sr",
	"sr-Cyrl-RS":     "sr",
	"sr-Cyrl-XK":     "sr",
	"sr-Latn":        "sr",
	"sr-Latn-BA":     "sr",
	"sr-Latn-ME":     "sr",
	"sr-Latn-RS":     "sr",
	"sr-Latn-XK":     "sr",
	"sv":             "sv",
	"sv-AX":          "sv",
	"sv-FI":          "sv",
	"sv-SE":          "sv",
	"sw":             "sw",
	"sw-CD":          "sw",
	"sw-KE":          "sw",
	"sw-TZ":          "sw",
	"sw-UG":          "sw",
	"ta":             "ta",
	"ta-IN":          "ta",
	"ta-LK":          "ta",
	"ta-MY":          "ta",
	"ta-SG":          "ta",
	"te":             "te",
	"te-IN":          "te",
	"teo":            "teo",
	"teo-KE":         "teo",
	"teo-UG":         "teo",
	"th":             "th",
	"th-TH":          "th",
	"ti":             "ti",
	"ti-ER":          "ti",
	"ti-ET":          "ti",
	"tk":             "tk",
	"tk-TM":          "tk",
	"to":             "to",
	"to-TO":          "to",
	"tr":             "tr",
	"tr-CY":          "tr",
	"tr-TR":          "tr",
	"twq":            "twq",
	"twq-NE":         "twq",
	"tzm":            "tzm",
	"tzm-MA":         "tzm",
	"ug":             "ug",
	"ug-CN":          "ug",
	"uk":             "uk",
	"uk-UA":          "uk",
	"ur":             "ur",
	"ur-IN":          "ur",
	"ur-PK":          "ur",
	"uz":             "uz",
	"uz-Arab":        "uz",
	"uz-Arab-AF":     "uz",
	"uz-Cyrl":        "uz",
	"uz-Cyrl-UZ":     "uz",
	"uz-Latn":        "uz",
	"uz-Latn-UZ":     "uz",
	"vai":            "vai",
	"vai-Latn":       "vai",
	"vai-Latn-LR":    "vai",
	"vai-Vaii":       "vai",
	"vai-Vaii-LR":    "vai",
	"vi":             "vi",
	"vi-VN":          "vi",
	"vo":             "vo",
	"vo-001":         "vo",
	"vun":            "vun",
	"vun-TZ":         "vun",
	"wae":            "wae",
	"wae-CH":         "wae",
	"xog":            "xog",
	"xog-UG":         "xog",
	"yav":            "yav",
	"yav-CM":         "yav",
	"yi":             "yi",
	"yi-001":         "yi",
	"yo":             "yo",
	"yo-BJ":          "yo",
	"yo-NG":          "yo",
	"yue":            "yue",
	"yue-HK":         "yue",
	"zgh":            "zgh",
	"zgh-MA":         "zgh",
	"zh":             "zh",
	"zh-Hans":        "zh",
	"zh-Hans-CN":     "zh",
	"zh-Hans-HK":     "zh",
	"zh-Hans-MO":     "zh",
	"zh-Hans-SG":     "zh",
	"zh-Hant":        "zh",
	"zh-Hant-HK":     "zh",
	"zh-Hant-MO":     "zh",
	"zh-Hant-TW":     "zh",
	"zu":             "zu",
	"zu-ZA":          "zu",
}

var langTags = map[string][]string{
	"af":   []string{"af", "af-NA", "af-ZA"},
	"agq":  []string{"agq", "agq-CM"},
	"ak":   []string{"ak", "ak-GH"},
	"am":   []string{"am", "am-ET"},
	"ar":   []string{"ar", "ar-001", "ar-AE", "ar-BH", "ar-DJ", "ar-DZ", "ar-EG", "ar-EH", "ar-ER", "ar-IL", "ar-IQ", "ar-JO", "ar-KM", "ar-KW", "ar-LB", "ar-LY", "ar-MA", "ar-MR", "ar-OM", "ar-PS", "ar-QA", "ar-SA", "ar-SD", "ar-SO", "ar-SS", "ar-SY", "ar-TD", "ar-TN", "ar-YE"},
	"as":   []string{"as", "as-IN"},
	"asa":  []string{"asa", "asa-TZ"},
	"ast":  []string{"ast", "ast-ES"},
	"az":   []string{"az", "az-Cyrl", "az-Cyrl-AZ", "az-Latn", "az-Latn-AZ"},
	"bas":  []string{"bas", "bas-CM"},
	"be":   []string{"be", "be-BY"},
	"bem":  []string{"bem", "bem-ZM"},
	"bez":  []string{"bez", "bez-TZ"},
	"bg":   []string{"bg", "bg-BG"},
	"bm":   []string{"bm", "bm-ML"},
	"bn":   []string{"bn", "bn-BD", "bn-IN"},
	"bo":   []string{"bo", "bo-CN", "bo-IN"},
	"br":   []string{"br", "br-FR"},
	"brx":  []string{"brx", "brx-IN"},
	"bs":   []string{"bs", "bs-Cyrl", "bs-Cyrl-BA", "bs-Latn", "bs-Latn-BA"},
	"ca":   []string{"ca", "ca-AD", "ca-ES", "ca-ES-VALENCIA", "ca-FR", "ca-IT"},
	"ce":   []string{"ce", "ce-RU"},
	"cgg":  []string{"cgg", "cgg-UG"},
	"chr":  []string{"chr", "chr-US"},
	"ckb":  []string{"ckb", "ckb-IQ", "ckb-IR"},
	"cs":   []string{"cs", "cs-CZ"},
	"cu":   []string{"cu", "cu-RU"},
	"cy":   []string{"cy", "cy-GB"},
	"da":   []string{"da", "da-DK", "da-GL"},
	"dav":  []string{"dav", "dav-KE"},
	"de":   []string{"de", "de-AT", "de-BE", "de-CH", "de-DE", "de-IT", "de-LI", "de-LU"},
	"dje":  []string{"dje", "dje-NE"},
	"dsb":  []string{"dsb", "dsb-DE"},
	"dua":  []string{"dua", "dua-CM"},
	"dyo":  []string{"dyo", "dyo-SN"},
	"dz":   []string{"dz", "dz-BT"},
	"ebu":  []string{"ebu", "ebu-KE"},
	"ee":   []string{"ee", "ee-GH", "ee-TG"},
	"el":   []string{"el", "el-CY", "el-GR"},
	"en":   []string{"en", "en-001", "en-150", "en-AG", "en-AI", "en-AS", "en-AT", "en-AU", "en-BB", "en-BE", "en-BI", "en-BM", "en-BS", "en-BW", "en-BZ", "en-CA", "en-CC", "en-CH", "en-CK", "en-CM", "en-CX", "en-CY", "en-DE", "en-DG", "en-DK", "en-DM", "en-ER", "en-FI", "en-FJ", "en-FK", "en-FM", "en-GB", "en-GD", "en-GG", "en-GH", "en-GI", "en-GM", "en-GU", "en-GY", "en-HK", "en-IE", "en-IL", "en-IM", "en-IN", "en-IO", "en-JE", "en-JM", "en-KE", "en-KI", "en-KN", "en-KY", "en-LC", "en-LR", "en-LS", "en-MG", "en-MH", "en-MO", "en-MP", "en-MS", "en-MT", "en-MU", "en-MW", "en-MY", "en-NA", "en-NF", "en-NG", "en-NL", "en-NR", "en-NU", "en-NZ", "en-PG", "en-PH", "en-PK", "en-PN", "en-PR", "en-PW", "en-RW", "en-SB", "en-SC", "en-SD", "en-SE", "en-SG", "en-SH", "en-SI", "en-SL", "en-SS", "en-SX", "en-SZ", "en-TC", "en-TK", "en-TO", "en-TT", "en-TV", "en-TZ", "en-UG", "en-UM", "en-US", "en-US-POSIX", "en-VC", "en-VG", "en-VI", "en-VU", "en-WS", "en-ZA", "en-ZM", "en-ZW"},
	"eo":   []string{"eo", "eo-001"},
	"es":   []string{"es", "es-419", "es-AR", "es-BO", "es-BR", "es-BZ", "es-CL", "es-CO", "es-CR", "es-CU", "es-DO", "es-EA", "es-EC", "es-ES", "es-GQ", "es-GT", "es-HN", "es-IC", "es-MX", "es-NI", "es-PA", "es-PE", "es-PH", "es-PR", "es-PY", "es-SV", "es-US", "es-UY", "es-VE"},
	"et":   []string{"et", "et-EE"},
	"eu":   []string{"eu", "eu-ES"},
	"ewo":  []string{"ewo", "ewo-CM"},
	"fa":   []string{"fa", "fa-AF", "fa-IR"},
	"ff":   []string{"ff", "ff-CM", "ff-GN", "ff-MR", "ff-SN"},
	"fi":   []string{"fi", "fi-FI"},
	"fil":  []string{"fil", "fil-PH"},
	"fo":   []string{"fo", "fo-DK", "fo-FO"},
	"fr":   []string{"fr", "fr-BE", "fr-BF", "fr-BI", "fr-BJ", "fr-BL", "fr-CA", "fr-CD", "fr-CF", "fr-CG", "fr-CH", "fr-CI", "fr-CM", "fr-DJ", "fr-DZ", "fr-FR", "fr-GA", "fr-GF", "fr-GN", "fr-GP", "fr-GQ", "fr-HT", "fr-KM", "fr-LU", "fr-MA", "fr-MC", "fr-MF", "fr-MG", "fr-ML", "fr-MQ", "fr-MR", "fr-MU", "fr-NC", "fr-NE", "fr-PF", "fr-PM", "fr-RE", "fr-RW", "fr-SC", "fr-SN", "fr-SY", "fr-TD", "fr-TG", "fr-TN", "fr-VU", "fr-WF", "fr-YT"},
	"fur":  []string{"fur", "fur-IT"},
	"fy":   []string{"fy", "fy-NL"},
	"ga":   []string{"ga", "ga-IE"},
	"gd":   []string{"gd", "gd-GB"},
	"gl":   []string{"gl", "gl-ES"},
	"gsw":  []string{"gsw", "gsw-CH", "gsw-FR", "gsw-LI"},
	"gu":   []string{"gu", "gu-IN"},
	"guz":  []string{"guz", "guz-KE"},
	"gv":   []string{"gv", "gv-IM"},
	"ha":   []string{"ha", "ha-GH", "ha-NE", "ha-NG"},
	"haw":  []string{"haw", "haw-US"},
	"he":   []string{"he", "he-IL"},
	"hi":   []string{"hi", "hi-IN"},
	"hr":   []string{"hr", "hr-BA", "hr-HR"},
	"hsb":  []string{"hsb", "hsb-DE"},
	"hu":   []string{"hu", "hu-HU"},
	"hy":   []string{"hy", "hy-AM"},
	"id":   []string{"id", "id-ID"},
	"ig":   []string{"ig", "ig-NG"},
	"ii":   []string{"ii", "ii-CN"},
	"is":   []string{"is", "is-IS"},
	"it":   []string{"it", "it-CH", "it-IT", "it-SM", "it-VA"},
	"ja":   []string{"ja", "ja-JP"},
	"jgo":  []string{"jgo", "jgo-CM"},
	"jmc":  []string{"jmc", "jmc-TZ"},
	"ka":   []string{"ka", "ka-GE"},
	"kab":  []string{"kab", "kab-DZ"},
	"kam":  []string{"kam", "kam-KE"},
	"kde":  []string{"kde", "kde-TZ"},
	"kea":  []string{"kea", "kea-CV"},
	"khq":  []string{"khq", "khq-ML"},
	"ki":   []string{"ki", "ki-KE"},
	"kk":   []string{"kk", "kk-KZ"},
	"kkj":  []string{"kkj", "kkj-CM"},
	"kl":   []string{"kl", "kl-GL"},
	"kln":  []string{"kln", "kln-KE"},
	"km":   []string{"km", "km-KH"},
	"kn":   []string{"kn", "kn-IN"},
	"ko":   []string{"ko", "ko-KP", "ko-KR"},
	"kok":  []string{"kok", "kok-IN"},
	"ks":   []string{"ks", "ks-IN"},
	"ksb":  []string{"ksb", "ksb-TZ"},
	"ksf":  []string{"ksf", "ksf-CM"},
	"ksh":  []string{"ksh", "ksh-DE"},
	"kw":   []string{"kw", "kw-GB"},
	"ky":   []string{"ky", "ky-KG"},
	"lag":  []string{"lag", "lag-TZ"},
	"lb":   []string{"lb", "lb-LU"},
	"lg":   []string{"lg", "lg-UG"},
	"lkt":  []string{"lkt", "lkt-US"},
	"ln":   []string{"ln", "ln-AO", "ln-CD", "ln-CF", "ln-CG"},
	"lo":   []string{"lo", "lo-LA"},
	"lrc":  []string{"lrc", "lrc-IQ", "lrc-IR"},
	"lt":   []string{"lt", "lt-LT"},
	"lu":   []string{"lu", "lu-CD"},
	"luo":  []string{"luo", "luo-KE"},
	"luy":  []string{"luy", "luy-KE"},
	"lv":   []string{"lv", "lv-LV"},
	"mas":  []string{"mas", "mas-KE", "mas-TZ"},
	"mer":  []string{"mer", "mer-KE"},
	"mfe":  []string{"mfe", "mfe-MU"},
	"mg":   []string{"mg", "mg-MG"},
	"mgh":  []string{"mgh", "mgh-MZ"},
	"mgo":  []string{"mgo", "mgo-CM"},
	"mk":   []string{"mk", "mk-MK"},
	"ml":   []string{"ml", "ml-IN"},
	"mn":   []string{"mn", "mn-MN"},
	"mr":   []string{"mr", "mr-IN"},
	"ms":   []string{"ms", "ms-BN", "ms-MY", "ms-SG"},
	"mt":   []string{"mt", "mt-MT"},
	"mua":  []string{"mua", "mua-CM"},
	"my":   []string{"my", "my-MM"},
	"mzn":  []string{"mzn", "mzn-IR"},
	"naq":  []string{"naq", "naq-NA"},
	"nb":   []string{"nb", "nb-NO", "nb-SJ"},
	"nd":   []string{"nd", "nd-ZW"},
	"nds":  []string{"nds", "nds-DE", "nds-NL"},
	"ne":   []string{"ne", "ne-IN", "ne-NP"},
	"nl":   []string{"nl", "nl-AW", "nl-BE", "nl-BQ", "nl-CW", "nl-NL", "nl-SR", "nl-SX"},
	"nmg":  []string{"nmg", "nmg-CM"},
	"nn":   []string{"nn", "nn-NO"},
	"nnh":  []string{"nnh", "nnh-CM"},
	"nus":  []string{"nus", "nus-SS"},
	"nyn":  []string{"nyn", "nyn-UG"},
	"om":   []string{"om", "om-ET", "om-KE"},
	"or":   []string{"or", "or-IN"},
	"os":   []string{"os", "os-GE", "os-RU"},
	"pa":   []string{"pa", "pa-Arab", "pa-Arab-PK", "pa-Guru", "pa-Guru-IN"},
	"pl":   []string{"pl", "pl-PL"},
	"prg":  []string{"prg", "prg-001"},
	"ps":   []string{"ps", "ps-AF"},
	"pt":   []string{"pt", "pt-AO", "pt-BR", "pt-CH", "pt-CV", "pt-GQ", "pt-GW", "pt-LU", "pt-MO", "pt-MZ", "pt-PT", "pt-ST", "pt-TL"},
	"qu":   []string{"qu", "qu-BO", "qu-EC", "qu-PE"},
	"rm":   []string{"rm", "rm-CH"},
	"rn":   []string{"rn", "rn-BI"},
	"ro":   []string{"ro", "ro-MD", "ro-RO"},
	"rof":  []string{"rof", "rof-TZ"},
	"root": []string{"root"},
	"ru":   []string{"ru", "ru-BY", "ru-KG", "ru-KZ", "ru-MD", "ru-RU", "ru-UA"},
	"rw":   []string{"rw", "rw-RW"},
	"rwk":  []string{"rwk", "rwk-TZ"},
	"sah":  []string{"sah", "sah-RU"},
	"saq":  []string{"saq", "saq-KE"},
	"sbp":  []string{"sbp", "sbp-TZ"},
	"se":   []string{"se", "se-FI", "se-NO", "se-SE"},
	"seh":  []string{"seh", "seh-MZ"},
	"ses":  []string{"ses", "ses-ML"},
	"sg":   []string{"sg", "sg-CF"},
	"shi":  []string{"shi", "shi-Latn", "shi-Latn-MA", "shi-Tfng", "shi-Tfng-MA"},
	"si":   []string{"si", "si-LK"},
	"sk":   []string{"sk", "sk-SK"},
	"sl":   []string{"sl", "sl-SI"},
	"smn":  []string{"smn", "smn-FI"},
	"sn":   []string{"sn", "sn-ZW"},
	"so":   []string{"so", "so-DJ", "so-ET", "so-KE", "so-SO"},
	"sq":   []string{"sq", "sq-AL", "sq-MK", "sq-XK"},
	"sr":   []string{"sr", "sr-Cyrl", "sr-Cyrl-BA", "sr-Cyrl-ME", "sr-Cyrl-RS", "sr-Cyrl-XK", "sr-Latn", "sr-Latn-BA", "sr-Latn-ME", "sr-Latn-RS", "sr-Latn-XK"},
	"sv":   []string{"sv", "sv-AX", "sv-FI", "sv-SE"},
	"sw":   []string{"sw", "sw-CD", "sw-KE", "sw-TZ", "sw-UG"},
	"ta":   []string{"ta", "ta-IN", "ta-LK", "ta-MY", "ta-SG"},
	"te":   []string{"te", "te-IN"},
	"teo":  []string{"teo", "teo-KE", "teo-UG"},
	"th":   []string{"th", "th-TH"},
	"ti":   []string{"ti", "ti-ER", "ti-ET"},
	"tk":   []string{"tk", "tk-TM"},
	"to":   []string{"to", "to-TO"},
	"tr":   []string{"tr", "tr-CY", "tr-TR"},
	"twq":  []string{"twq", "twq-NE"},
	"tzm":  []string{"tzm", "tzm-MA"},
	"ug":   []string{"ug", "ug-CN"},
	"uk":   []string{"uk", "uk-UA"},
	"ur":   []string{"ur", "ur-IN", "ur-PK"},
	"uz":   []string{"uz", "uz-Arab", "uz-Arab-AF", "uz-Cyrl", "uz-Cyrl-UZ", "uz-Latn", "uz-Latn-UZ"},
	"vai":  []string{"vai", "vai-Latn", "vai-Latn-LR", "vai-Vaii", "vai-Vaii-LR"},
	"vi":   []string{"vi", "vi-VN"},
	"vo":   []string{"vo", "vo-001"},
	"vun":  []string{"vun", "vun-TZ"},
	"wae":  []string{"wae", "wae-CH"},
	"xog":  []string{"xog", "xog-UG"},
	"yav":  []string{"yav", "yav-CM"},
	"yi":   []string{"yi", "yi-001"},
	"yo":   []string{"yo", "yo-BJ", "yo-NG"},
	"yue":  []string{"yue", "yue-HK"},
	"zgh":  []string{"zgh", "zgh-MA"},
	"zh":   []string{"zh", "zh-Hans", "zh-Hans-CN", "zh-Hans-HK", "zh-Hans-MO", "zh-Hans-SG", "zh-Hant", "zh-Hant-HK", "zh-Hant-MO", "zh-Hant-TW"},
	"zu":   []string{"zu", "zu-ZA"},
}

var regions = map[string]string{
	"af-NA":          "NA",
	"af-ZA":          "ZA",
	"agq-CM":         "CM",
	"ak-GH":          "GH",
	"am-ET":          "ET",
	"ar-001":         "001",
	"ar-AE":          "AE",
	"ar-BH":          "BH",
	"ar-DJ":          "DJ",
	"ar-DZ":          "DZ",
	"ar-EG":          "EG",
	"ar-EH":          "EH",
	"ar-ER":          "ER",
	"ar-IL":          "IL",
	"ar-IQ":          "IQ",
	"ar-JO":          "JO",
	"ar-KM":          "KM",
	"ar-KW":          "KW",
	"ar-LB":          "LB",
	"ar-LY":          "LY",
	"ar-MA":          "MA",
	"ar-MR":          "MR",
	"ar-OM":          "OM",
	"ar-PS":          "PS",
	"ar-QA":          "QA",
	"ar-SA":          "SA",
	"ar-SD":          "SD",
	"ar-SO":          "SO",
	"ar-SS":          "SS",
	"ar-SY":          "SY",
	"ar-TD":          "TD",
	"ar-TN":          "TN",
	"ar-YE":          "YE",
	"as-IN":          "IN",
	"asa-TZ":         "TZ",
	"ast-ES":         "ES",
	"az-Cyrl-AZ":     "AZ",
	"az-Latn-AZ":     "AZ",
	"bas-CM":         "CM",
	"be-BY":          "BY",
	"bem-ZM":         "ZM",
	"bez-TZ":         "TZ",
	"bg-BG":          "BG",
	"bm-ML":          "ML",
	"bn-BD":          "BD",
	"bn-IN":          "IN",
	"bo-CN":          "CN",
	"bo-IN":          "IN",
	"br-FR":          "FR",
	"brx-IN":         "IN",
	"bs-Cyrl-BA":     "BA",
	"bs-Latn-BA":     "BA",
	"ca-AD":          "AD",
	"ca-ES":          "ES",
	"ca-ES-VALENCIA": "ES",
	"ca-FR":          "FR",
	"ca-IT":          "IT",
	"ce-RU":          "RU",
	"cgg-UG":         "UG",
	"chr-US":         "US",
	"ckb-IQ":         "IQ",
	"ckb-IR":         "IR",
	"cs-CZ":          "CZ",
	"cu-RU":          "RU",
	"cy-GB":          "GB",
	"da-DK":          "DK",
	"da-GL":          "GL",
	"dav-KE":         "KE",
	"de-AT":          "AT",
	"de-BE":          "BE",
	"de-CH":          "CH",
	"de-DE":          "DE",
	"de-IT":          "IT",
	"de-LI":          "LI",
	"de-LU":          "LU",
	"dje-NE":         "NE",
	"dsb-DE":         "DE",
	"dua-CM":         "CM",
	"dyo-SN":         "SN",
	"dz-BT":          "BT",
	"ebu-KE":         "KE",
	"ee-GH":          "GH",
	"ee-TG":          "TG",
	"el-CY":          "CY",
	"el-GR":          "GR",
	"en-001":         "001",
	"en-150":         "150",
	"en-AG":          "AG",
	"en-AI":          "AI",
	"en-AS":          "AS",
	"en-AT":          "AT",
	"en-AU":          "AU",
	"en-BB":          "BB",
	"en-BE":          "BE",
	"en-BI":          "BI",
	"en-BM":          "BM",
	"en-BS":          "BS",
	"en-BW":          "BW",
	"en-BZ":          "BZ",
	"en-CA":          "CA",
	"en-CC":          "CC",
	"en-CH":          "CH",
	"en-CK":          "CK",
	"en-CM":          "CM",
	"en-CX":          "CX",
	"en-CY":          "CY",
	"en-DE":          "DE",
	"en-DG":          "DG",
	"en-DK":          "DK",
	"en-DM":          "DM",
	"en-ER":          "ER",
	"en-FI":          "FI",
	"en-FJ":          "FJ",
	"en-FK":          "FK",
	"en-FM":          "FM",
	"en-GB":          "GB",
	"en-GD":          "GD",
	"en-GG":          "GG",
	"en-GH":          "GH",
	"en-GI":          "GI",
	"en-GM":          "GM",
	"en-GU":          "GU",
	"en-GY":          "GY",
	"en-HK":          "HK",
	"en-IE":          "IE",
	"en-IL":          "IL",
	"en-IM":          "IM",
	"en-IN":          "IN",
	"en-IO":          "IO",
	"en-JE":          "JE",
	"en-JM":          "JM",
	"en-KE":          "KE",
	"en-KI":          "KI",
	"en-KN":          "KN",
	"en-KY":          "KY",
	"en-LC":          "LC",
	"en-LR":          "LR",
	"en-LS":          "LS",
	"en-MG":          "MG",
	"en-MH":          "MH",
	"en-MO":          "MO",
	"en-MP":          "MP",
	"en-MS":          "MS",
	"en-MT":          "MT",
	"en-MU":          "MU",
	"en-MW":          "MW",
	"en-MY":          "MY",
	"en-NA":          "NA",
	"en-NF":          "NF",
	"en-NG":          "NG",
	"en-NL":          "NL",
	"en-NR":          "NR",
	"en-NU":          "NU",
	"en-NZ":          "NZ",
	"en-PG":          "PG",
	"en-PH":          "PH",
	"en-PK":          "PK",
	"en-PN":          "PN",
	"en-PR":          "PR",
	"en-PW":          "PW",
	"en-RW":          "RW",
	"en-SB":          "SB",
	"en-SC":          "SC",
	"en-SD":          "SD",
	"en-SE":          "SE",
	"en-SG":          "SG",
	"en-SH":          "SH",
	"en-SI":          "SI",
	"en-SL":          "SL",
	"en-SS":          "SS",
	"en-SX":          "SX",
	"en-SZ":          "SZ",
	"en-TC":          "TC",
	"en-TK":          "TK",
	"en-TO":          "TO",
	"en-TT":          "TT",
	"en-TV":          "TV",
	"en-TZ":          "TZ",
	"en-UG":          "UG",
	"en-UM":          "UM",
	"en-US":          "US",
	"en-US-POSIX":    "US",
	"en-VC":          "VC",
	"en-VG":          "VG",
	"en-VI":          "VI",
	"en-VU":          "VU",
	"en-WS":          "WS",
	"en-ZA":          "ZA",
	"en-ZM":          "ZM",
	"en-ZW":          "ZW",
	"eo-001":         "001",
	"es-419":         "419",
	"es-AR":          "AR",
	"es-BO":          "BO",
	"es-BR":          "BR",
	"es-BZ":          "BZ",
	"es-CL":          "CL",
	"es-CO":          "CO",
	"es-CR":          "CR",
	"es-CU":          "CU",
	"es-DO":          "DO",
	"es-EA":          "EA",
	"es-EC":          "EC",
	"es-ES":          "ES",
	"es-GQ":          "GQ",
	"es-GT":          "GT",
	"es-HN":          "HN",
	"es-IC":          "IC",
	"es-MX":          "MX",
	"es-NI":          "NI",
	"es-PA":          "PA",
	"es-PE":          "PE",
	"es-PH":          "PH",
	"es-PR":          "PR",
	"es-PY":          "PY",
	"es-SV":          "SV",
	"es-US":          "US",
	"es-UY":          "UY",
	"es-VE":          "VE",
	"et-EE":          "EE",
	"eu-ES":          "ES",
	"ewo-CM":         "CM",
	"fa-AF":          "AF",
	"fa-IR":          "IR",
	"ff-CM":          "CM",
	"ff-GN":          "GN",
	"ff-MR":          "MR",
	"ff-SN":          "SN",
	"fi-FI":          "FI",
	"fil-PH":         "PH",
	"fo-DK":          "DK",
	"fo-FO":          "FO",
	"fr-BE":          "BE",
	"fr-BF":          "BF",
	"fr-BI":          "BI",
	"fr-BJ":          "BJ",
	"fr-BL":          "BL",
	"fr-CA":          "CA",
	"fr-CD":          "CD",
	"fr-CF":          "CF",
	"fr-CG":          "CG",
	"fr-CH":          "CH",
	"fr-CI":          "CI",
	"fr-CM":          "CM",
	"fr-DJ":          "DJ",
	"fr-DZ":          "DZ",
	"fr-FR":          "FR",
	"fr-GA":          "GA",
	"fr-GF":          "GF",
	"fr-GN":          "GN",
	"fr-GP":          "GP",
	"fr-GQ":          "GQ",
	"fr-HT":          "HT",
	"fr-KM":          "KM",
	"fr-LU":          "LU",
	"fr-MA":          "MA",
	"fr-MC":          "MC",
	"fr-MF":          "MF",
	"fr-MG":          "MG",
	"fr-ML":          "ML",
	"fr-MQ":          "MQ",
	"fr-MR":          "MR",
	"fr-MU":          "MU",
	"fr-NC":          "NC",
	"fr-NE":          "NE",
	"fr-PF":          "PF",
	"fr-PM":          "PM",
	"fr-RE":          "RE",
	"fr-RW":          "RW",
	"fr-SC":          "SC",
	"fr-SN":          "SN",
	"fr-SY":          "SY",
	"fr-TD":          "TD",
	"fr-TG":          "TG",
	"fr-TN":          "TN",
	"fr-VU":          "VU",
	"fr-WF":          "WF",
	"fr-YT":          "YT",
	"fur-IT":         "IT",
	"fy-NL":          "NL",
	"ga-IE":          "IE",
	"gd-GB":          "GB",
	"gl-ES":          "ES",
	"gsw-CH":         "CH",
	"gsw-FR":         "FR",
	"gsw-LI":         "LI",
	"gu-IN":          "IN",
	"guz-KE":         "KE",
	"gv-IM":          "IM",
	"ha-GH":          "GH",
	"ha-NE":          "NE",
	"ha-NG":          "NG",
	"haw-US":         "US",
	"he-IL":          "IL",
	"hi-IN":          "IN",
	"hr-BA":          "BA",
	"hr-HR":          "HR",
	"hsb-DE":         "DE",
	"hu-HU":          "HU",
	"hy-AM":          "AM",
	"id-ID":          "ID",
	"ig-NG":          "NG",
	"ii-CN":          "CN",
	"is-IS":          "IS",
	"it-CH":          "CH",
	"it-IT":          "IT",
	"it-SM":          "SM",
	"it-VA":          "VA",
	"ja-JP":          "JP",
	"jgo-CM":         "CM",
	"jmc-TZ":         "TZ",
	"ka-GE":          "GE",
	"kab-DZ":         "DZ",
	"kam-KE":         "KE",
	"kde-TZ":         "TZ",
	"kea-CV":         "CV",
	"khq-ML":         "ML",
	"ki-KE":          "KE",
	"kk-KZ":          "KZ",
	"kkj-CM":         "CM",
	"kl-GL":          "GL",
	"kln-KE":         "KE",
	"km-KH":          "KH",
	"kn-IN":          "IN",
	"ko-KP":          "KP",
	"ko-KR":          "KR",
	"kok-IN":         "IN",
	"ks-IN":          "IN",
	"ksb-TZ":         "TZ",
	"ksf-CM":         "CM",
	"ksh-DE":         "DE",
	"kw-GB":          "GB",
	"ky-KG":          "KG",
	"lag-TZ":         "TZ",
	"lb-LU":          "LU",
	"lg-UG":          "UG",
	"lkt-US":         "US",
	"ln-AO":          "AO",
	"ln-CD":          "CD",
	"ln-CF":          "CF",
	"ln-CG":          "CG",
	"lo-LA":          "LA",
	"lrc-IQ":         "IQ",
	"lrc-IR":         "IR",
	"lt-LT":          "LT",
	"lu-CD":          "CD",
	"luo-KE":         "KE",
	"luy-KE":         "KE",
	"lv-LV":          "LV",
	"mas-KE":         "KE",
	"mas-TZ":         "TZ",
	"mer-KE":         "KE",
	"mfe-MU":         "MU",
	"mg-MG":          "MG",
	"mgh-MZ":         "MZ",
	"mgo-CM":         "CM",
	"mk-MK":          "MK",
	"ml-IN":          "IN",
	"mn-MN":          "MN",
	"mr-IN":          "IN",
	"ms-BN":          "BN",
	"ms-MY":          "MY",
	"ms-SG":          "SG",
	"mt-MT":          "MT",
	"mua-CM":         "CM",
	"my-MM":          "MM",
	"mzn-IR":         "IR",
	"naq-NA":         "NA",
	"nb-NO":          "NO",
	"nb-SJ":          "SJ",
	"nd-ZW":          "ZW",
	"nds-DE":         "DE",
	"nds-NL":         "NL",
	"ne-IN":          "IN",
	"ne-NP":          "NP",
	"nl-AW":          "AW",
	"nl-BE":          "BE",
	"nl-BQ":          "BQ",
	"nl-CW":          "CW",
	"nl-NL":          "NL",
	"nl-SR":          "SR",
	"nl-SX":          "SX",
	"nmg-CM":         "CM",
	"nn-NO":          "NO",
	"nnh-CM":         "CM",
	"nus-SS":         "SS",
	"nyn-UG":         "UG",
	"om-ET":          "ET",
	"om-KE":          "KE",
	"or-IN":          "IN",
	"os-GE":          "GE",
	"os-RU":          "RU",
	"pa-Arab-PK":     "PK",
	"pa-Guru-IN":     "IN",
	"pl-PL":          "PL",
	"prg-001":        "001",
	"ps-AF":          "AF",
	"pt-AO":          "AO",
	"pt-BR":          "BR",
	"pt-CH":          "CH",
	"pt-CV":          "CV",
	"pt-GQ":          "GQ",
	"pt-GW":          "GW",
	"pt-LU":          "LU",
	"pt-MO":          "MO",
	"pt-MZ":          "MZ",
	"pt-PT":          "PT",
	"pt-ST":          "ST",
	"pt-TL":          "TL",
	"qu-BO":          "BO",
	"qu-EC":          "EC",
	"qu-PE":          "PE",
	"rm-CH":          "CH",
	"rn-BI":          "BI",
	"ro-MD":          "MD",
	"ro-RO":          "RO",
	"rof-TZ":         "TZ",
	"ru-BY":          "BY",
	"ru-KG":          "KG",
	"ru-KZ":          "KZ",
	"ru-MD":          "MD",
	"ru-RU":          "RU",
	"ru-UA":          "UA",
	"rw-RW":          "RW",
	"rwk-TZ":         "TZ",
	"sah-RU":         "RU",
	"saq-KE":         "KE",
	"sbp-TZ":         "TZ",
	"se-FI":          "FI",
	"se-NO":          "NO",
	"se-SE":          "SE",
	"seh-MZ":         "MZ",
	"ses-ML":         "ML",
	"sg-CF":          "CF",
	"shi-Latn-MA":    "MA",
	"shi-Tfng-MA":    "MA",
	"si-LK":          "LK",
	"sk-SK":          "SK",
	"sl-SI":          "SI",
	"smn-FI":         "FI",
	"sn-ZW":          "ZW",
	"so-DJ":          "DJ",
	"so-ET":          "ET",
	"so-KE":          "KE",
	"so-SO":          "SO",
	"sq-AL":          "AL",
	"sq-MK":          "MK",
	"sq-XK":          "XK",
	"sr-Cyrl-BA":     "BA",
	"sr-Cyrl-ME":     "ME",
	"sr-Cyrl-RS":     "RS",
	"sr-Cyrl-XK":     "XK",
	"sr-Latn-BA":     "BA",
	"sr-Latn-ME":     "ME",
	"sr-Latn-RS":     "RS",
	"sr-Latn-XK":     "XK",
	"sv-AX":          "AX",
	"sv-FI":          "FI",
	"sv-SE":          "SE",
	"sw-CD":          "CD",
	"sw-KE":          "KE",
	"sw-TZ":          "TZ",
	"sw-UG":          "UG",
	"ta-IN":          "IN",
	"ta-LK":          "LK",
	"ta-MY":          "MY",
	"ta-SG":          "SG",
	"te-IN":          "IN",
	"teo-KE":         "KE",
	"teo-UG":         "UG",
	"th-TH":          "TH",
	"ti-ER":          "ER",
	"ti-ET":          "ET",
	"tk-TM":          "TM",
	"to-TO":          "TO",
	"tr-CY":          "CY",
	"tr-TR":          "TR",
	"twq-NE":         "NE",
	"tzm-MA":         "MA",
	"ug-CN":          "CN",
	"uk-UA":          "UA",
	"ur-IN":          "IN",
	"ur-PK":          "PK",
	"uz-Arab-AF":     "AF",
	"uz-Cyrl-UZ":     "UZ",
	"uz-Latn-UZ":     "UZ",
	"vai-Latn-LR":    "LR",
	"vai-Vaii-LR":    "LR",
	"vi-VN":          "VN",
	"vo-001":         "001",
	"vun-TZ":         "TZ",
	"wae-CH":         "CH",
	"xog-UG":         "UG",
	"yav-CM":         "CM",
	"yi-001":         "001",
	"yo-BJ":          "BJ",
	"yo-NG":          "NG",
	"yue-HK":         "HK",
	"zgh-MA":         "MA",
	"zh-Hans-CN":     "CN",
	"zh-Hans-HK":     "HK",
	"zh-Hans-MO":     "MO",
	"zh-Hans-SG":     "SG",
	"zh-Hant-HK":     "HK",
	"zh-Hant-MO":     "MO",
	"zh-Hant-TW":     "TW",
	"zu-ZA":          "ZA",
}
